name: safar
description: A new Flutter project.
publish_to: "none"

version: 1.0.1+4
#todo1 increment every time 

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: "3.13.8"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0

  bot_toast: ^4.1.3

  calendar_date_picker2: ^0.5.3

  chopper: ^7.0.8

  cupertino_icons: ^1.0.6

  equatable: ^2.0.5

  flutter_bloc: ^8.1.3

  flutter_datetime_picker_plus: ^2.1.0

  flutter_dialogs: ^3.0.0

  flutter_downloader: ^1.11.4

  flutter_gen: ^5.3.2

  flutter_localization: ^0.1.14

  flutter_screenutil: ^5.9.0

  flutter_svg: ^2.0.9

  file_picker: ^8.0.0+1
 
  http: ^1.1.0

  hive:

  hive_flutter:

  open_file: ^3.3.2

  package_info_plus: ^4.2.0

  path_provider: ^2.1.1

  intl: ^0.18.1

  percent_indicator: ^4.2.3

  permission_handler: ^11.0.1

  json_annotation: 4.8.1

  logging: ^1.2.0

  local_auth: ^2.1.3

  shared_preferences: ^2.2.2

  shimmer: ^3.0.0

  url_launcher: ^6.1.14


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner: ^2.4.6

  chopper_generator: ^7.0.6

  flutter_gen_runner: ^5.3.2

  json_serializable: ^6.7.1

  hive_generator: 

flutter_gen:
  output: lib/gen/ 
  line_length: 80 

  # Optional
  integrations:
    flutter_svg: true
    rive: true
  
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/icons/staff_icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf


  
  # Firebase plugins
  # firebase_core: ^2.21.0
  # firebase_messaging: ^14.7.3
  # better_player: ^0.0.83
  # flutter_local_notifications: ^16.1.0

